### ISSUE TITLE
Transition from update to manage does not show update

### ISSUE THREAD

**Issue by culbert** [nerc-project/regapp#1]

**Comment by waygil** [comment]
@jtriley @joachimweyl , can you let me know if this still requires Jim's attention or if there are other external blocks?  If not can we close the issue?

**Comment by joachimweyl** [comment]
@waygil yes, we need @culbert to let us know if this is still an issue that requires work. We can close it if not and if yes we need further description.

**Comment by culbert** [comment]
This issue has been resolved.
