### ISSUE TITLE
Enable University of Toronto acces for CILogon 

### ISSUE THREAD

**Issue by msdisme** [nerc-project/regapp#40]
We are currently collaborating with researchers from BU, Red Hat, and the University of Toronto. Since the feature described in https://github.com/nerc-project/regapp/issues/38 is not yet active, could we enable the University of Toronto.

**Comment by culbert** [comment]
Please have a user from University of Toronto visit https://cilogon.org and login (presumably using the IdP which they intend to use for NERC). Have them open the accordions labeled "User Attributes" and "Identity Provider Attributes" and take a screenshot of the information presented there and send that along to us. I'll add the info from there to our allow list.

**Comment by msdisme** [comment]
will do - thanks Jim!

**Comment by msdisme** [comment]
@culbert here is the screenshot - thanks!!

![toronto](https://github.com/nerc-project/regapp/assets/6126065/00c0fdcb-ac3c-4467-8eb7-7b087c52a02a)

**Comment by msdisme** [comment]
msd sent mail to confirm that the u toronto works on test cluster

**Comment by msdisme** [comment]
@culbert  Got feedback that account creation worked.  Thanks!!
