### ISSUE TITLE
Enable Yale University access for CILogon

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/regapp#43]
## Motivation
We are currently collaborating with researchers from Yale University. Since the feature described in https://github.com/nerc-project/regapp/issues/38 is not yet active, could we enable Yale University?

## Completion Criteria
Yale University users are able to log in.

## Description
- [ ] @Milstein Please have a user from Yale visit https://cilogon.org/ and login (presumably using the IdP which they intend to use for NERC). Have them open the accordions labeled "User Attributes" and "Identity Provider Attributes" and take a screenshot of the information presented there and send that along to us.
- [ ] @culbert add the info from there to our allowed list.

## Completion dates
Desired - 2023-12-08
Required - TBD

**Comment by waygil** [comment]
Provided additional instructions to Robert Bjornson in[ ticket 1989](https://mghpcc.supportsystem.com/scp/tickets.php?id=5977) to provide screenshot to us.

Wayne

**Comment by waygil** [comment]
Received screenshots from Yale.  Attached here:  
![Yale IdP Attributes](https://github.com/nerc-project/regapp/assets/8452015/51c945e6-2f96-4d91-ae66-1af43997e803)
![Yale Use Attributes](https://github.com/nerc-project/regapp/assets/8452015/9ef14c3d-9e4d-4ae5-9dfa-9f5331b23e6f)

**Comment by joachimweyl** [comment]
@culbert do these screenshots provide the detail we need?

**Comment by joachimweyl** [comment]
The test site confirmed, waiting for prod confirmation
