### ISSUE TITLE
Enable Dartmouth University access for CILogon

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/regapp#44]
## Motivation
We are currently collaborating with researchers from Dartmouth University. Since the feature described in https://github.com/nerc-project/regapp/issues/38 is not yet active, could we enable Dartmouth University?

## Completion Criteria
Yale University users are able to log in.

## Description
- [x] @Milstein get screenshot
- [ ] @culbert add Dartmouth

## Completion dates
Desired - 2023-12-08
Required - TBD

**Comment by msdisme** [comment]
@waygil looked and dartmouth is in.  Thanks @culbert !

**Comment by joachimweyl** [comment]
This was closed by accident because University of Massachusetts - Dartmouth was added. We are still waiting on adding Dartmouth.

**Comment by joachimweyl** [comment]
@Milstein double checking, was this a request for Dartmouth or the University of Massachusetts - Dartmouth?

**Comment by joachimweyl** [comment]
@Milstein Please have a user from Dartmouth visit https://cilogon.org/ and login (presumably using the IdP which they intend to use for NERC). Have them open the accordions labeled "User Attributes" and "Identity Provider Attributes" and take a screenshot of the information presented there and send that along to us. I'll add the info from there to our allow list.

**Comment by Milstein** [comment]
<img width="463" alt="image" src="https://github.com/nerc-project/regapp/assets/144645/f0e2dcb9-4ea2-4106-bf0c-a906069727c4">

**Comment by Milstein** [comment]
The test site confirmed, waiting for prod confirmation
