### ISSUE TITLE
Disable the username change while registering user account.

### ISSUE THREAD

**Issue by Milstein** [nerc-project/regapp#47]
- This is creating conflict during batch users upload.
- We can set username default to what OIDC meta data fetch for email address.

**Comment by joachimweyl** [comment]
@culbert what is the next step for this?

**Comment by waygil** [comment]
@Milstein, can you let me know if this still requires Jim's attention or if there are other external blocks?  If not can we close the issue?

**Comment by Milstein** [comment]
@waygil : this requires @culbert's attention to test and verify.

**Comment by joachimweyl** [comment]
@Milstein I believe Jim has approved and merged the PR, please link the PR here and if the merge was in the Maintenance on the 14th please close this issue, if we need another maintenance for this please state so and we will plan one to get this PR included.
